AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - Certificate creation

Parameters:
  DomainName:
    Type: String
  Region:
    Type: String
    Default: 'us-east-1'
  CFNCustomProvider:
    Type: String

Resources:
  Certificate:
    Type: Custom::Certificate
    Properties:
      DomainName: !Sub '*.${DomainName}'
      Region: !Ref Region
      ValidationMethod: DNS
      ServiceToken: !Ref 'CFNCustomProvider'

  IssuedCertificate:
    Type: Custom::IssuedCertificate
    Properties:
      CertificateArn: !Ref Certificate
      ServiceToken: !Ref 'CFNCustomProvider'

  CertificateDNSRecord:
    Type: Custom::CertificateDNSRecord
    Properties:
      CertificateArn: !Ref Certificate
      DomainName: !Sub '*.${DomainName}'
      ServiceToken: !Ref 'CFNCustomProvider'

  DomainValidationRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
        - Name: !GetAtt CertificateDNSRecord.Name
          Type: !GetAtt CertificateDNSRecord.Type
          TTL: 60
          Weight: 1
          SetIdentifier: !Ref Certificate
          ResourceRecords:
            - !GetAtt CertificateDNSRecord.Value

Outputs:
  DNSRecord:
    Value: !Sub '${CertificateDNSRecord.Name} ${CertificateDNSRecord.Type} ${CertificateDNSRecord.Value}'
  CertificateArn: 
    Value: !Ref Certificate
