AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - Cert Provider with DNS validation
Transform: AWS::Serverless-2016-10-31

Parameters:
  SubDomain:
    Description: The part of a website address before your DomainName - e.g. www or img
    Type: String
    Default: www
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String
  Environment:
    Type: String
    Description: 'Environment name'
    Default: 'dev'
    AllowedValues:
      - dev
      - staging
      - prod

Conditions:
  SubDomainExists: !Not [!Equals [!Ref SubDomain, ""]]

Resources:
  CopyCustomResource:
    Type: 'AWS::CloudFormation::CustomResource'
    Properties:
      ServiceToken: !GetAtt CopyFunction.Arn 
      ServiceTimeout: 30

  S3BucketLogs:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 
        # TODO: see if we can use name instead of fullDomain
        - '${FullDomain}-logs-${Environment}-${AWS::AccountId}-${AWS::Region}'
        # TODO: extract if possible
        - FullDomain: !If
            - SubDomainExists
            - !Sub '${SubDomain}.${DomainName}'
            - !Ref DomainName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        # TODO: add environmant tag
        - Key: Solution
          Value: ACFS3

  S3BucketRoot:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 
        - '${FullDomain}-root-${Environment}-${AWS::AccountId}-${AWS::Region}'
        - FullDomain: !If
            - SubDomainExists
            - !Sub '${SubDomain}.${DomainName}'
            - !Ref DomainName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref 'S3BucketLogs'
        LogFilePrefix: 'origin/'
      Tags:
        - Key: Solution
          Value: ACFS3

  CopyLayerVersion:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: ../witch.zip
      CompatibleRuntimes:
        - nodejs20.x

  CopyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3CopyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub
                    - arn:aws:s3:::${TargetBucket}/*
                    - TargetBucket: !Ref S3BucketRoot
                  - !Sub
                    - arn:aws:s3:::${TargetBucket}
                    - TargetBucket: !Ref S3BucketRoot

  CopyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../www
      Environment:
        Variables:
          BUCKET: !Ref S3BucketRoot
      Handler: witch.staticHandler
      Layers:
        - !Ref CopyLayerVersion
      Role: !GetAtt CopyRole.Arn
      Runtime: nodejs20.x
      Timeout: 300

Outputs:
  S3BucketRoot:
    Description: Website bucket
    Value: !Ref S3BucketRoot
  S3BucketRootName:
    Description: Website bucket name
    Value: !GetAtt S3BucketRoot.DomainName
  S3BucketRootArn:
    Description: Website bucket locator
    Value: !GetAtt S3BucketRoot.Arn
  S3BucketLogs:
    Description: Logging bucket
    Value: !Ref S3BucketLogs
  S3BucketLogsName:
    Description: Logging bucket Name
    Value: !GetAtt S3BucketLogs.DomainName
  CopyFunction:
    Description: S3 helper function
    Value: !GetAtt CopyFunction.Arn
